### ISSUE TITLE
not working with draw sprite?

### ISSUE THREAD

**Issue by SKITTLE6969** [trclassic92/tr-lumberjack#11]
doesn't this work with draw sprite on?

**Comment by trclassic92** [comment]
Not be default... 


You have to make edits for it to work with it.

**Comment by Smokey-city-rp** [comment]
cannot get lumber depo menu to open with third eye

**Comment by trclassic92** [comment]
we dont support drawsprite

**Comment by Smokey-city-rp** [comment]
i already fixed this and made it work. thanks for the reply
