### ISSUE TITLE
[BUG] You can pick up log while truck is full

### ISSUE THREAD

**Issue by asapverneri** [trclassic92/tr-lumberjack#15]
Hello, I found a bug where you can pick up a log even if truck is full. It might be confusing for some players

**Comment by trclassic92** [comment]
> Hello, I found a bug where you can pick up a log even if truck is full. It might be confusing for some players

This is not a bug, There were some changes made when 2.0.5 was released to help ensure *players* came across this issue.

A player should still be able to pick up the logs, as nothing should stop them from doing so, but if the truck is Full, there is really no way for them to add them to the truck itself.

**Comment by trclassic92** [comment]
Closed for the following

Not a bug and is intended this way
