### ISSUE TITLE
[bug] vehicle not returning

### ISSUE THREAD

**Issue by luneargr** [trclassic92/tr-lumberjack#16]
Hello , i have a problem when i get a truck and i want to return it doesn't return it is there an issue with it? I tried the latest version of the script  i am using qbx-core and also bridge is enabled.

**Comment by trclassic92** [comment]
> i get a truck and i want to return it doesn't return it is there an issue with it?

There is correctly no option for this so.

this is **NOT** a bug. 

Just hasn't been added yet

**Comment by trclassic92** [comment]
I have added this to my trello since this has been requested by more then one person via discord. 

Any questions regarding this feel free to join our discord to keep up to date on it
