### ISSUE TITLE
Depot Ped Not Spawning

### ISSUE THREAD

**Issue by AJOfficial95** [trclassic92/tr-lumberjack#2]
The ped thats supposed to be at the lumberjack depot isnt spawning. Any help is much aprpeciated 
![image](https://user-images.githubusercontent.com/57418667/159249719-eb5213f8-7126-47bd-a104-6d92dd7a7bad.png)
https://i.imgur.com/VJGtpaz.png

**Comment by trclassic92** [comment]
This issue was fixed yesterday. You have to update the script.

**Comment by AJOfficial95** [comment]
ok thankyou

**Comment by trclassic92** [comment]
> ok thankyou
> 
> 

😅 you are more than welcome to join my personal discord for updates on this scripts and or any other once's on my github so you are not behind in the future. 😉
