### ISSUE TITLE
[SUGGESTION] Add trailer support

### ISSUE THREAD

**Issue by P4R4NORM4L** [trclassic92/tr-lumberjack#4]
Was wondering if you could add trailer support to the script? I have this logging trailer which would be awesome for me :)

**Comment by P4R4NORM4L** [comment]
Very rudimentary but I got it to work.

client\main.lua line 250
`RegisterNetEvent('tr-lumberjack:vehicle', function()
    local vehicle = LumberDepo.Vehicle
    local coords = LumberDepo.VehicleCoords
    local trailer = LumberDepo.Trailer
    local tcoords = LumberDepo.TrailerCoords
    local TR = PlayerPedId()
    RequestModel(vehicle)
    RequestModel(trailer)
    while not HasModelLoaded(vehicle) and HasModelLoaded(trailer) do
        Wait(0)
    end
    if not IsAnyVehicleNearPoint(coords.x, coords.y, coords.z, 5.0) then
        local JobVehicle = CreateVehicle(vehicle, coords, 45.0, true, false)
        local JobTrailer = CreateVehicle(trailer, tcoords, 45.0, true, false)
        SetVehicleHasBeenOwnedByPlayer(JobVehicle,  true)
        SetVehicleHasBeenOwnedByPlayer(JobTrailer,  true)
        SetEntityAsMissionEntity(JobVehicle,  true,  true)
        SetEntityAsMissionEntity(JobTrailer,  true,  true)
        exports['LegacyFuel']:SetFuel(JobVehicle, 100.0)
        local id = NetworkGetNetworkIdFromEntity(JobVehicle)
        local id2 = NetworkGetNetworkIdFromEntity(JobTrailer)
        DoScreenFadeOut(1500)
        Wait(1500)
        SetNetworkIdCanMigrate(id, true)
        SetNetworkIdCanMigrate(id2, true)
        TaskWarpPedIntoVehicle(TR, JobVehicle, -1)
        TriggerEvent("vehiclekeys:client:SetOwner", QBCore.Functions.GetPlate(JobVehicle))
        DoScreenFadeIn(1500)
        Wait(2000)
        TriggerServerEvent('qb-phone:server:sendNewMail', {
            sender = Config.Alerts["phone_sender"],
            subject = Config.Alerts["phone_subject"],
            message = Config.Alerts["phone_message"],
            })
    else
        QBCore.Functions.Notify(Config.Alerts["depo_blocked"], "error")
    end
end)`

config .lua after line 19
`   Trailer = 'manaclog',
    TrailerCoords = vector4(1201.56, -1328.01, 35.23, 360.00), `

**Comment by trclassic92** [comment]
> Very rudimentary but I got it to work.
> 
> client\main.lua line 250 `RegisterNetEvent('tr-lumberjack:vehicle', function() local vehicle = LumberDepo.Vehicle local coords = LumberDepo.VehicleCoords local trailer = LumberDepo.Trailer local tcoords = LumberDepo.TrailerCoords local TR = PlayerPedId() RequestModel(vehicle) RequestModel(trailer) while not HasModelLoaded(vehicle) and HasModelLoaded(trailer) do Wait(0) end if not IsAnyVehicleNearPoint(coords.x, coords.y, coords.z, 5.0) then local JobVehicle = CreateVehicle(vehicle, coords, 45.0, true, false) local JobTrailer = CreateVehicle(trailer, tcoords, 45.0, true, false) SetVehicleHasBeenOwnedByPlayer(JobVehicle, true) SetVehicleHasBeenOwnedByPlayer(JobTrailer, true) SetEntityAsMissionEntity(JobVehicle, true, true) SetEntityAsMissionEntity(JobTrailer, true, true) exports['LegacyFuel']:SetFuel(JobVehicle, 100.0) local id = NetworkGetNetworkIdFromEntity(JobVehicle) local id2 = NetworkGetNetworkIdFromEntity(JobTrailer) DoScreenFadeOut(1500) Wait(1500) SetNetworkIdCanMigrate(id, true) SetNetworkIdCanMigrate(id2, true) TaskWarpPedIntoVehicle(TR, JobVehicle, -1) TriggerEvent("vehiclekeys:client:SetOwner", QBCore.Functions.GetPlate(JobVehicle)) DoScreenFadeIn(1500) Wait(2000) TriggerServerEvent('qb-phone:server:sendNewMail', { sender = Config.Alerts["phone_sender"], subject = Config.Alerts["phone_subject"], message = Config.Alerts["phone_message"], }) else QBCore.Functions.Notify(Config.Alerts["depo_blocked"], "error") end end)`
> 
> config .lua after line 19 ` Trailer = 'manaclog', TrailerCoords = vector4(1201.56, -1328.01, 35.23, 360.00),`

I will review this and see if it will be added 👍

**Comment by P4R4NORM4L** [comment]
Nice Thanks
